Repository mezzio/mezzio-hal, pull requests merged in 2020-12, with the labels that each got.

#16 Make all entity keys available as route parameters
  CHANGELOG.md
  src/ResourceGenerator/RouteBasedResourceStrategy.php
  test/ResourceGenerator/NestedCollectionResourceGenerationTest.php
  test/ResourceGenerator/ResourceWithNestedInstancesTest.php
  test/ResourceGenerator/RouteBasedCollectionWithRouteParamsTest.php
  test/ResourceGenerator/UrlBasedCollectionWithRouteParamsTest.php
  test/ResourceGeneratorTest.php
Labels: Enhancement

#13 Added an entity properties to route placeholders mapping
  CHANGELOG.md
  docs/book/factories.md
  docs/book/resource-generator.md
  src/Metadata/Exception/InvalidConfigException.php
  src/Metadata/RouteBasedResourceMetadata.php
  src/Metadata/RouteBasedResourceMetadataFactory.php
  src/ResourceGenerator/RouteBasedResourceStrategy.php
  test/Metadata/MetadataMapFactoryTest.php
  test/ResourceGeneratorTest.php
Labels: Enhancement

#27 Remove deprecated functionality in preparation for 2.0.0
  CHANGELOG.md
  docs/book/factories.md
  docs/book/resource-generator.md
  src/Metadata/RouteBasedResourceMetadata.php
  src/Metadata/RouteBasedResourceMetadataFactory.php
  test/Metadata/MetadataMapFactoryTest.php
  test/ResourceGenerator/ResourceWithSelfReferringInstanceTest.php
  test/ResourceGenerator/RouteBasedCollectionWithRouteParamsTest.php
  test/ResourceGenerator/UrlBasedCollectionWithRouteParamsTest.php
  test/ResourceGeneratorTest.php
Labels: BC Break, Feature Removal

#29 Provide Psalm integration
  .travis.yml
  CHANGELOG.md
  composer.json
  psalm-baseline.xml
  psalm.xml.dist
  src/HalResource.php
  src/Link.php
  src/LinkCollection.php
  src/Metadata/MetadataMapFactory.php
  src/Renderer/XmlRenderer.php
  test/HalResourceTest.php
  test/HalResponseFactoryFactoryTest.php
  test/HalResponseFactoryTest.php
  test/LinkGenerator/MezzioUrlGeneratorFactoryTest.php
  test/LinkGenerator/MezzioUrlGeneratorTest.php
  test/LinkGeneratorFactoryTest.php
  test/LinkGeneratorTest.php
  test/LinkTest.php
  test/Metadata/MetadataMapFactoryTest.php
  test/Metadata/MetadataMapTest.php
  test/PHPUnitDeprecatedAssertions.php
  test/Renderer/JsonRendererTest.php
  test/Renderer/XmlRendererTest.php
  test/ResourceGenerator/DoctrinePaginatorTest.php
  test/ResourceGenerator/NestedCollectionResourceGenerationTest.php
  test/ResourceGenerator/ResourceWithNestedInstancesTest.php
  test/ResourceGenerator/RouteBasedCollectionWithRouteParamsTest.php
  test/ResourceGenerator/UrlBasedCollectionWithRouteParamsTest.php
  test/ResourceGeneratorFactoryTest.php
  test/ResourceGeneratorTest.php
Labels: BC Break, Enhancement

#30 V2 documentation
  docs/book/cookbook/generating-custom-links-in-middleware.md
  docs/book/cookbook/generating-custom-resources.md
  docs/book/cookbook/path-segregated-uri-generation.md
  docs/book/doctrine.md
  docs/book/factories.md
  docs/book/hal.md
  docs/book/intro.md
  docs/book/links-and-resources.md
  docs/book/representations.md
  docs/book/resource-generator.md
  docs/book/v1/cookbook/generating-custom-links-in-middleware.md
  docs/book/v1/cookbook/generating-custom-resources.md
  docs/book/v1/cookbook/path-segregated-uri-generation.md
  docs/book/v1/doctrine.md
  docs/book/v1/factories.md
  docs/book/v1/hal.md
  docs/book/v1/index.md
  docs/book/v1/links-and-resources.md
  docs/book/v1/representations.md
  docs/book/v1/resource-generator.md
  docs/book/v2/cookbook/generating-custom-links-in-middleware.md
  docs/book/v2/cookbook/generating-custom-resources.md
  docs/book/v2/cookbook/path-segregated-uri-generation.md
  docs/book/v2/doctrine.md
  docs/book/v2/factories.md
  docs/book/v2/hal.md
  docs/book/v2/index.md
  docs/book/v2/links-and-resources.md
  docs/book/v2/migration.md
  docs/book/v2/representations.md
  docs/book/v2/resource-generator.md
  mkdocs.yml
Labels: Documentation

#31 Fix broken mkdocs.yml
  mkdocs.yml
Labels: Bug, Documentation
